# The name of the author of the portfolio.
author: Kara Netterville

# The URL where the portfolio is hosted.
url: http://karanetterville.com


# The title of the site.
title: KaraNetterville

# Permalink settings
permalink: /:categories/:title
