# The name of the author of the portfolio.
author: Zachary Lewis

# The URL where the portfolio is hosted.
url: http://zacharylew.is

# The subdirectory containing your portfolio.
baseurl: /simplefolio

# The title of the site.
title: Simplefolio

# Permalink settings
permalink: /:categories/:title
